// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: nameNode.proto

package grpc_namenode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NNPlayG2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number   int64  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	PlayerId string `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *NNPlayG2) Reset() {
	*x = NNPlayG2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nameNode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NNPlayG2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NNPlayG2) ProtoMessage() {}

func (x *NNPlayG2) ProtoReflect() protoreflect.Message {
	mi := &file_nameNode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NNPlayG2.ProtoReflect.Descriptor instead.
func (*NNPlayG2) Descriptor() ([]byte, []int) {
	return file_nameNode_proto_rawDescGZIP(), []int{0}
}

func (x *NNPlayG2) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *NNPlayG2) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type NNPlayG1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Numbers  []int64 `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	PlayerId string  `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *NNPlayG1) Reset() {
	*x = NNPlayG1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nameNode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NNPlayG1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NNPlayG1) ProtoMessage() {}

func (x *NNPlayG1) ProtoReflect() protoreflect.Message {
	mi := &file_nameNode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NNPlayG1.ProtoReflect.Descriptor instead.
func (*NNPlayG1) Descriptor() ([]byte, []int) {
	return file_nameNode_proto_rawDescGZIP(), []int{1}
}

func (x *NNPlayG1) GetNumbers() []int64 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *NNPlayG1) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type NNPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *NNPlayer) Reset() {
	*x = NNPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nameNode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NNPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NNPlayer) ProtoMessage() {}

func (x *NNPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_nameNode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NNPlayer.ProtoReflect.Descriptor instead.
func (*NNPlayer) Descriptor() ([]byte, []int) {
	return file_nameNode_proto_rawDescGZIP(), []int{2}
}

func (x *NNPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type NNConfirmation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processed bool `protobuf:"varint,1,opt,name=processed,proto3" json:"processed,omitempty"`
}

func (x *NNConfirmation) Reset() {
	*x = NNConfirmation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nameNode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NNConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NNConfirmation) ProtoMessage() {}

func (x *NNConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_nameNode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NNConfirmation.ProtoReflect.Descriptor instead.
func (*NNConfirmation) Descriptor() ([]byte, []int) {
	return file_nameNode_proto_rawDescGZIP(), []int{3}
}

func (x *NNConfirmation) GetProcessed() bool {
	if x != nil {
		return x.Processed
	}
	return false
}

var File_nameNode_proto protoreflect.FileDescriptor

var file_nameNode_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3e, 0x0a, 0x08, 0x4e, 0x4e, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x32, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x44, 0x0a, 0x08, 0x4e, 0x4e, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x31, 0x12, 0x1c, 0x0a, 0x07,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x42, 0x02, 0x10,
	0x01, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x08, 0x4e, 0x4e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2e,
	0x0a, 0x0e, 0x4e, 0x4e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x32, 0x97,
	0x01, 0x0a, 0x0b, 0x4e, 0x4e, 0x53, 0x71, 0x75, 0x69, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x2d,
	0x0a, 0x0d, 0x4e, 0x4e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x47, 0x31, 0x12,
	0x09, 0x2e, 0x4e, 0x4e, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x31, 0x1a, 0x0f, 0x2e, 0x4e, 0x4e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x2d, 0x0a,
	0x0d, 0x4e, 0x4e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x47, 0x32, 0x12, 0x09,
	0x2e, 0x4e, 0x4e, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x32, 0x1a, 0x0f, 0x2e, 0x4e, 0x4e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x10,
	0x4e, 0x4e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x47, 0x31,
	0x12, 0x09, 0x2e, 0x4e, 0x4e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x1a, 0x09, 0x2e, 0x4e, 0x4e,
	0x50, 0x6c, 0x61, 0x79, 0x47, 0x31, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2e, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nameNode_proto_rawDescOnce sync.Once
	file_nameNode_proto_rawDescData = file_nameNode_proto_rawDesc
)

func file_nameNode_proto_rawDescGZIP() []byte {
	file_nameNode_proto_rawDescOnce.Do(func() {
		file_nameNode_proto_rawDescData = protoimpl.X.CompressGZIP(file_nameNode_proto_rawDescData)
	})
	return file_nameNode_proto_rawDescData
}

var file_nameNode_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nameNode_proto_goTypes = []interface{}{
	(*NNPlayG2)(nil),       // 0: NNPlayG2
	(*NNPlayG1)(nil),       // 1: NNPlayG1
	(*NNPlayer)(nil),       // 2: NNPlayer
	(*NNConfirmation)(nil), // 3: NNConfirmation
}
var file_nameNode_proto_depIdxs = []int32{
	1, // 0: NNSquidGame.NNSendPlaysG1:input_type -> NNPlayG1
	0, // 1: NNSquidGame.NNSendPlaysG2:input_type -> NNPlayG2
	2, // 2: NNSquidGame.NNReceivePlaysG1:input_type -> NNPlayer
	3, // 3: NNSquidGame.NNSendPlaysG1:output_type -> NNConfirmation
	3, // 4: NNSquidGame.NNSendPlaysG2:output_type -> NNConfirmation
	1, // 5: NNSquidGame.NNReceivePlaysG1:output_type -> NNPlayG1
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nameNode_proto_init() }
func file_nameNode_proto_init() {
	if File_nameNode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nameNode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NNPlayG2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nameNode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NNPlayG1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nameNode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NNPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nameNode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NNConfirmation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nameNode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nameNode_proto_goTypes,
		DependencyIndexes: file_nameNode_proto_depIdxs,
		MessageInfos:      file_nameNode_proto_msgTypes,
	}.Build()
	File_nameNode_proto = out.File
	file_nameNode_proto_rawDesc = nil
	file_nameNode_proto_goTypes = nil
	file_nameNode_proto_depIdxs = nil
}
