// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: dataNode.proto

package grpc_datanode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DNPlayG2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number   int64  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	PlayerId string `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Node     string `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *DNPlayG2) Reset() {
	*x = DNPlayG2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataNode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNPlayG2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNPlayG2) ProtoMessage() {}

func (x *DNPlayG2) ProtoReflect() protoreflect.Message {
	mi := &file_dataNode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNPlayG2.ProtoReflect.Descriptor instead.
func (*DNPlayG2) Descriptor() ([]byte, []int) {
	return file_dataNode_proto_rawDescGZIP(), []int{0}
}

func (x *DNPlayG2) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *DNPlayG2) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *DNPlayG2) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type DNPlayG1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Numbers  []int64 `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	PlayerId string  `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Node     string  `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *DNPlayG1) Reset() {
	*x = DNPlayG1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataNode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNPlayG1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNPlayG1) ProtoMessage() {}

func (x *DNPlayG1) ProtoReflect() protoreflect.Message {
	mi := &file_dataNode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNPlayG1.ProtoReflect.Descriptor instead.
func (*DNPlayG1) Descriptor() ([]byte, []int) {
	return file_dataNode_proto_rawDescGZIP(), []int{1}
}

func (x *DNPlayG1) GetNumbers() []int64 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *DNPlayG1) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *DNPlayG1) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type DNPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *DNPlayer) Reset() {
	*x = DNPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataNode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNPlayer) ProtoMessage() {}

func (x *DNPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_dataNode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNPlayer.ProtoReflect.Descriptor instead.
func (*DNPlayer) Descriptor() ([]byte, []int) {
	return file_dataNode_proto_rawDescGZIP(), []int{2}
}

func (x *DNPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type DNConfirmation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processed bool `protobuf:"varint,1,opt,name=processed,proto3" json:"processed,omitempty"`
}

func (x *DNConfirmation) Reset() {
	*x = DNConfirmation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataNode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNConfirmation) ProtoMessage() {}

func (x *DNConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_dataNode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNConfirmation.ProtoReflect.Descriptor instead.
func (*DNConfirmation) Descriptor() ([]byte, []int) {
	return file_dataNode_proto_rawDescGZIP(), []int{3}
}

func (x *DNConfirmation) GetProcessed() bool {
	if x != nil {
		return x.Processed
	}
	return false
}

var File_dataNode_proto protoreflect.FileDescriptor

var file_dataNode_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x52, 0x0a, 0x08, 0x44, 0x4e, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x32, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x22, 0x58, 0x0a, 0x08, 0x44, 0x4e, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x31,
	0x12, 0x1c, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x42, 0x02, 0x10, 0x01, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x26,
	0x0a, 0x08, 0x44, 0x4e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x0e, 0x44, 0x4e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x32, 0x96, 0x01, 0x0a, 0x0b, 0x44, 0x4e, 0x53, 0x71, 0x75,
	0x69, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x0d, 0x44, 0x4e, 0x53, 0x65, 0x6e, 0x64,
	0x50, 0x6c, 0x61, 0x79, 0x73, 0x47, 0x31, 0x12, 0x09, 0x2e, 0x44, 0x4e, 0x50, 0x6c, 0x61, 0x79,
	0x47, 0x31, 0x1a, 0x0f, 0x2e, 0x44, 0x4e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0c, 0x44, 0x4e, 0x53, 0x65, 0x6e, 0x64, 0x50,
	0x6c, 0x61, 0x79, 0x47, 0x32, 0x12, 0x09, 0x2e, 0x44, 0x4e, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x32,
	0x1a, 0x0f, 0x2e, 0x44, 0x4e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x10, 0x44, 0x4e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x50, 0x6c, 0x61, 0x79, 0x73, 0x47, 0x31, 0x12, 0x09, 0x2e, 0x44, 0x4e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x1a, 0x09, 0x2e, 0x44, 0x4e, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x31, 0x22, 0x00, 0x42,
	0x12, 0x5a, 0x10, 0x2e, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x6e,
	0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dataNode_proto_rawDescOnce sync.Once
	file_dataNode_proto_rawDescData = file_dataNode_proto_rawDesc
)

func file_dataNode_proto_rawDescGZIP() []byte {
	file_dataNode_proto_rawDescOnce.Do(func() {
		file_dataNode_proto_rawDescData = protoimpl.X.CompressGZIP(file_dataNode_proto_rawDescData)
	})
	return file_dataNode_proto_rawDescData
}

var file_dataNode_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dataNode_proto_goTypes = []interface{}{
	(*DNPlayG2)(nil),       // 0: DNPlayG2
	(*DNPlayG1)(nil),       // 1: DNPlayG1
	(*DNPlayer)(nil),       // 2: DNPlayer
	(*DNConfirmation)(nil), // 3: DNConfirmation
}
var file_dataNode_proto_depIdxs = []int32{
	1, // 0: DNSquidGame.DNSendPlaysG1:input_type -> DNPlayG1
	0, // 1: DNSquidGame.DNSendPlayG2:input_type -> DNPlayG2
	2, // 2: DNSquidGame.DNReceivePlaysG1:input_type -> DNPlayer
	3, // 3: DNSquidGame.DNSendPlaysG1:output_type -> DNConfirmation
	3, // 4: DNSquidGame.DNSendPlayG2:output_type -> DNConfirmation
	1, // 5: DNSquidGame.DNReceivePlaysG1:output_type -> DNPlayG1
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dataNode_proto_init() }
func file_dataNode_proto_init() {
	if File_dataNode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dataNode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNPlayG2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataNode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNPlayG1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataNode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataNode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNConfirmation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dataNode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataNode_proto_goTypes,
		DependencyIndexes: file_dataNode_proto_depIdxs,
		MessageInfos:      file_dataNode_proto_msgTypes,
	}.Build()
	File_dataNode_proto = out.File
	file_dataNode_proto_rawDesc = nil
	file_dataNode_proto_goTypes = nil
	file_dataNode_proto_depIdxs = nil
}
